version: "3"

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    hostname: camunda
    restart: unless-stopped
    ports:
      - 38080:8080
      - 38000:8000
      - 39404:9404
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.camunda.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.camunda.rule=Host(`camunda.${HOSTNAME}`)
      - traefik.http.routers.camunda_secure.rule=Host(`camunda.${HOSTNAME}`)
      - traefik.http.routers.camunda_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT:? TRAEFIK_HTTPS_ENDPOINT must be provided}
      - traefik.http.routers.camunda_secure.tls.certresolver=le
      - traefik.http.services.camunda.loadbalancer.server.port=8080
      - traefik.http.routers.admin-router.service=admin-service
    
networks:
  web:
    name: web
    external: true