FROM openjdk:19-jdk-alpine

ENV camunda_modeler_version="camunda-modeler-4.12.0-linux-x64"

RUN apk add --no-cache wget 

WORKDIR /usr/share/camunda

RUN wget --no-verbose  https://downloads.camunda.cloud/release/camunda-modeler/4.12.0/${camunda_modeler_version}.tar.gz && \
    tar -zxf ${camunda_modeler_version}.tar.gz && \
    rm ${camunda_modeler_version}.tar.gz 

WORKDIR /usr/share/camunda/${camunda_modeler_version}

EXPOSE 8080

RUN ls -la && pwd
CMD /usr/share/camunda/camunda-modeler-4.12.0-linux-x64/camunda-modeler