version: '3.9'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - KILL
      - NET_BIND_SERVICE
      - DAC_READ_SEARCH
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    command: 
      --api.insecure=true
      --providers.docker

networks:
  web:
    driver: bridge
    name: web
