version: '3'

services:
  hashivault:
    image: vault:latest
    ports:
      - "127.0.0.1:${VAULT_PORT:-8200}:8200"
    environment:
      VAULT_ADDR: "${HOSTNAME}:${VAULT_PORT:-8200}"
      VAULT_DEV_ROOT_TOKEN_ID: "${VAULT_ROOT_TOKEN}"
    cap_add:
      - IPC_LOCK
    networks:
      - web
      #vault-network:
      #  ipv4_address: 172.21.0.10
      #  aliases:
      #    - vault-server
    labels:
      - traefik.enable=true
      
      - traefik.http.routers.hashivault.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.hashivault.rule=Host(`files.${HOSTNAME}`)

      - traefik.http.routers.hashivault_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.hashivault_secure.rule=Host(`files.${HOSTNAME}`)
      - traefik.http.routers.hashivault_secure.tls.certresolver=le

      - traefik.http.services.hashivault.loadbalancer.server.port=8200


networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
  web:
    external: true